version: '3.9'

services:
  nginx:
    container_name: laravel-nginx
    image: nginx:latest
    ports:
      - '8080:80'
    volumes:
      - ./:/var/www/website
      - ./default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php-fpm
      - postgres
    networks:
      - internal

  php-fpm:
    user: "1000:1000"
    container_name: laravel-php-fpm
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /var/www/website
    volumes:
      - ./:/var/www/website
    networks:
      - internal

  postgres:
    container_name: laravel-postgres
    image: postgres:latest
    restart: no
    environment:
      POSTGRES_PASSWORD: mysecretpassword
    volumes:
      - /var/lib/postgresql/data
    networks:
      - internal

networks:
  internal:
    driver: bridge

